name: Crypto-V deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: npm installation
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      
    name: SonarQube Scan

  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@master
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ http://34.201.244.194/ }}
        login: ${{ secrets.SONAR_TOKEN }}
        projectBaseDir: ${{ . }}
        projectName: ${{ crypto-v }}

      

