name: Crypto-V deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: npm installation
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      
      - name: sonarqube-code-analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        run: |
         ./gradlew sonarqube \
            -Dsonar.host.url=http://34.201.244.194/ \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
